//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int FUID { get; set; }
        public int SUID { get; set; }
        public int MUID { get; set; }
    
        public virtual Användare Användare { get; set; }
        public virtual Användare Användare1 { get; set; }
    }
}
