//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProfilInfo
    {
        public int PID { get; set; }
        public string FNamn { get; set; }
        public string ENamn { get; set; }
        public Nullable<int> Ålder { get; set; }
        public Nullable<int> Kön { get; set; }
        public string Intresse { get; set; }
        public string URL { get; set; }
        public int UID { get; set; }
    
        public virtual Användare Användare { get; set; }
    }
}
